version: '3.3'

# Ports exposed for the services:
# db, vault, rabbitmq 
# only needed for external access (Debugging)

services:
  db:
    image: "postgres:12"
    environment:
      - "POSTGRES_USER=echome"
      - "POSTGRES_PASSWORD=echome"
      - "POSTGRES_DB=echome"
    volumes:
      - echome_postgres_data:/var/lib/postgresql/data/
    ports:
      - 15432:5432
  api:
    build: .
    environment:
      - DATABASE_URL=postgres://echome:echome@db:5432/echome
    ports:
      - 18000:8000
    depends_on:
      - db
      - vault
      - rabbitmq
    volumes:
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock 
      - /etc/echome:/etc/echome
      - /mnt:/mnt
    devices:
      - /dev/kvm
    privileged: true
  vault:
    image: "vault:1.8.2"
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - echome_vault_data:/vault/
      - ./vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault-config.json
  rabbitmq:
    image: "rabbitmq:3.9"
    hostname: echome-rabbit
    ports:
      - "5672:5672"

volumes:
  echome_postgres_data:
  echome_vault_data:
