version: '3.3'

services:
  db:
    image: "postgres:12"
    environment:
      - "POSTGRES_USER=echome"
      - "POSTGRES_PASSWORD=echome"
      - "POSTGRES_DB=echome"
    volumes:
      - echome_postgres_data:/var/lib/postgresql/data/
    ports:
      - 15432:5432
  api:
    build: .
    environment:
      - DATABASE_URL=postgres://echome:echome@host.docker.internal:15432/echome
    ports:
      - 18000:8000
    depends_on:
      - db

volumes:
  echome_postgres_data: