#cloud-config
chpasswd: {expire: false}
ssh_pwauth: false
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3RLyBbu6hL57oQV3WoIEsJFkYyIAVHiH405GU8It1HLC3NXH+tGzJLYKTTbvGwJPdIFAWVMOcv97xxfQjhK2+7cMCxdrYReeL3yBv3KUANYgbBaoOcg0ZC05WI4vB+qfdDzpygzIe2sTO7rM0/58qttt4lQbJdVNq8S1rGEyuhTMRZEVwc84U5Jj+dsDgPmryTp49WwlKwzc3sI2NkmJcBoGdyptbcyX/OssyaKk+cY4ImXQb2q2lfpfSXN/yQw6BgO4lXfQBmc6jf13TeZo9ltJCZZ9v9PDs5ttmZouwOIJwQxwzGgXPYVJFtg0Vaz9CSFQjgpONl5Z8+PE94oIT
write_files:
- encoding: b64
  content: ewogICAgImNvbnRyb2xsZXJfaXAiOiAiMTcyLjE2LjkuNzAiLAogICAgImNsdXN0ZXJfbmFtZSI6ICJrdWJlLTAxMjM0NTY3IiwKICAgICJjbHVzdGVyX3ZlcnNpb24iOiAiMS4yMi4wIiwKICAgICJjbHVzdGVyX3NlcnZpY2Vfc3VibmV0IjogIjEwLjk2LjAuMC8xMiIsCiAgICAidG9rZW5fdHRsIjogIjBoMW0wcyIKfQo=
  owner: root:root
  path: /root/cluster_info.yaml
  permissions: '0644'
- encoding: b64
  content: IyEvYmluL2Jhc2gKCmFwdCB1cGRhdGUgJiYgYXB0IHVwZ3JhZGUgLXkKCmFwdCBpbnN0YWxsIHB5dGhvbjMtcGlwCnBpcCBpbnN0YWxsIGoyY2xpCgojIEdlbmVyYXRlIHRoZSBrdWJlYWRtIGNvbmZpZyBmaWxlCktVQkVBRE1fVE9LRU49JChrdWJlYWRtIHRva2VuIGdlbmVyYXRlKQpleHBvcnQgS1VCRUFETV9UT0tFTgpqMiAtZiB5YW1sIHRlbXBsYXRlLnlhbWwgdmFsdWVzLmpzb24gLW8ga3ViZV9pbml0LnlhbWwKCiMgSW5pdCB0aGUgY2x1c3Rlciwgc2tpcHBpbmcgY2VydHMKa3ViZWFkbSBpbml0IC0tY29uZmlnIGt1YmVfaW5pdC55YW1sCg==
  owner: root:root
  path: /root/init_kube_debian.sh
  permissions: '0775'
runcmd:
 - [ /root/init_kube_debian.sh ]
