---
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: $controller_addr
    token: $token
    unsafeSkipCAVerification: false
    caCertHashes:
    - $ca_cert_hash
  timeout: 5m0s
nodeRegistration:
  taints: null
